kind: pipeline
name: build base images

steps:
    - name: setup
      image: docker:dind
      volumes:
      - name: dockersock
      - path: /var/run
      environment:
        AWS_ACCESS_KEY_ID:
            from_secret: AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY:
            from_secret: AWS_SECRET_ACCESS_KEY
      commands:
        - apk add curl
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip -q awscliv2.zip
        - ./aws/install
        - aws --version
        - aws s3 sync s3://forgerock7-binaries /tmp
        - cd /tmp
        - unzip -q Amster-7.0.0.zip -d amster
        - unzip -q DS-7.0.0.zip -d ds 
        - unzip -q IG-7.0.0.zip -d ig
        - unzip -q IDM-7.0.1.zip -d idm
        - unzip -q AM-7.0.0.zip -d amazonaws
        - cd amster/samples/docker
        - ./setup.sh
        - docker build --tag amster:7.0 .

# services:
#     - name: docker
#         image: docker:dind
#         privileged: true
#         volumes:
#         - name: dockersock
#         path: /var/run

# volumes:
#     - name: dockersock
#         temp: {}