kind: pipeline
name: build base images

steps:
    - name: build  
      image: node
      volumes:
        - name: cache
          path: /fr
      environment:
        AWS_ACCESS_KEY_ID:
            from_secret: AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY:
            from_secret: AWS_SECRET_ACCESS_KEY
      commands:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - ./aws/install
        - aws s3 sync s3://forgerock7-binaries . --no-progress
        - unzip -q Amster-7.0.0.zip -d amster
        # - unzip -q DS-7.0.0.zip -d ds
        # - unzip -q IG-7.0.0.zip -d ig 
        # - unzip -q IDM-7.0.1.zip -d idm 
        # - unzip -q AM-7.0.0.zip -d am
        - cd amster/samples/docker
        - ./setup.sh
        - ls amster/samples/docker/build
      
    - name: publish  
      image: plugins/ecr
      volumes:
        - name: cache
          path: /fr
      settings:
        access_key:
          from_secret: AWS_ACCESS_KEY_ID
        secret_key:
          from_secret: AWS_SECRET_ACCESS_KEY 
        create_repository: true
        repo: 499815288658.dkr.ecr.eu-west-1.amazonaws.com/dronetest
        registry: 499815288658.dkr.ecr.eu-west-1.amazonaws.com
        dockerfile: amster/samples/docker/Dockerfile
        region: eu-west-1
