kind: pipeline
name: build base images

steps:
    - name: setup
      image: docker:dind
      volumes:
      - name: dockersock
      - path: /var/run
      environment:
        AWS_ACCESS_KEY_ID:
            from_secret: AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY:
            from_secret: AWS_SECRET_ACCESS_KEY
      commands:
        - apk add --no-cache bash build-base ca-certificates curl gettext git libffi-dev linux-headers make musl-dev openldap-dev openssh-client python3 py-pip python3-dev rsync tzdata
        - pip3 install --upgrade pip
        - pip3 install awscli boto3 'PyYAML<=3.13,>=3.10' aws-sam-cli docker-compose --upgrade
        # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        # - unzip -q awscliv2.zip
        # - ./aws/install
        - aws --version
        - aws s3 sync s3://forgerock7-binaries .
        - cd /tmp
        - unzip -q Amster-7.0.0.zip DS-7.0.0.zip IG-7.0.0.zip IDM-7.0.1.zip AM-7.0.0.zip
        - cd amster-7.0.0/samples/docker
        - ./setup.sh
        - docker build --tag amster:7.0 .

# services:
#     - name: docker
#         image: docker:dind
#         privileged: true
#         volumes:
#         - name: dockersock
#         path: /var/run

# volumes:
#     - name: dockersock
#         temp: {}