kind: pipeline
name: build base images

steps:
  - name: pull-binaries
    image: amidodevelopment/drone-runner-image:latest
    commands:
      - aws s3 sync s3://forgerock7-binaries . --no-progress
    when:
      event: push
      branch: master

  - name: build-base-amster
    image: amidodevelopment/drone-runner-image:latest
    commands:
      - unzip -q Amster-7.0.*.zip -d amster
      - cd amster/samples/docker
      - ./setup.sh
    when:
      event: push
      branch: master

  - name: build-empty-am
    image: amidodevelopment/drone-runner-image:latest
    commands:
      - unzip -q AM-7.0.*.zip -d am
      - cd am/openam/samples/docker
      - chmod u+x setup.sh
      - sed -i'.tmp' -e 's/[Oo]pen[Aa][Mm]/AM/g' setup.sh
      - sed -i'.tmp' -e 's/7.0.0/7.0.1/g' setup.sh
      - ./setup.sh
      - cd images/am-empty
      - chmod u+x docker-entrypoint.sh
      - chmod u+x scripts/*
      - sed -i'.tmp' -e 's/openam.war/AM.war/g' Dockerfile
      - cd ../am-base
      - chmod u+x docker-entrypoint.sh
      - chmod u+x scripts/*
      - sed -i'.tmp' -e 's/FROM amster/FROM '499815288658.dkr.ecr.eu-west-1.amazonaws.com'\\/id\\/amster/g' Dockerfile
      - sed -i'.tmp' -e 's/FROM am-empty/FROM '499815288658.dkr.ecr.eu-west-1.amazonaws.com'\\/id\\/am-base/g' Dockerfile
    when:
      event: push
      branch: master

  - name: publish-am-empty
    image: plugins/ecr
    settings:
      repo: id/am-base
      registry: 499815288658.dkr.ecr.eu-west-1.amazonaws.com
      region: eu-west-1
      context: am/openam/samples/docker/images/am-empty
      dockerfile: am/openam/samples/docker/images/am-empty/Dockerfile
      force_tag: true
      tags:
        - "latest"
        - "${DRONE_COMMIT_SHA}"
    when:
      event: push
      branch: master

  - name: build-base-ds
    image: openjdk:11
    commands:
      - mkdir ds
      - unzip -q DS-7.0.*.zip -d ds
      - cd ds/opendj
      - ./samples/docker/setup.sh
    when:
      event: push
      branch: master

  - name: build-base-idm
    image: alpine:3.12.1
    commands:
      - mkdir idm
      - unzip -q IDM-7.0.*.zip -d idm
      - cd idm/openidm
    when:
      event: push
      branch: master

  - name: publish-base-amster
    image: plugins/ecr
    settings:
      repo: id/amster
      registry: 499815288658.dkr.ecr.eu-west-1.amazonaws.com
      region: eu-west-1
      context: amster/samples/docker
      dockerfile: amster/samples/docker/Dockerfile
      tags:
        - "build-${DRONE_BUILD_NUMBER}"
        - "${DRONE_COMMIT_SHA}"
        - "link-${DRONE_BUILD_NUMBER}"
        - "latest"
    when:
      event: push
      branch: master

image_pull_secrets:
  - dockerconfig
