kind: pipeline
name: build base images

steps:
    - name: setup
      image: node:latest
      environment:
        AWS_ACCESS_KEY_ID:
            from_secret: AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY:
            from_secret: AWS_SECRET_ACCESS_KEY
      commands:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip -q awscliv2.zip
        - ./aws/install
        - aws --version
        - aws s3 cp s3://forgerock7-binaries/ /tmp
        - ls /tmp